id: PD6E5AF10
initial_creation_type: input
source_metadata:
  title: Chögyal Pakpa Lodrö Gyaltsen
  language: bo
  description: 'Texts by and about the great Sakya master Chögyal Pakpa Lodrö Gyaltsen
    (chos rgyal ’phags pa blo gros rgyal mtshan, 1235–1280):'
  volume:
    35fb74096a8b4d2b932cbbfbf6888e17:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Dhāraṇī
    4db92d2da97144859b04edcbb59a873c:
      title: Short Maṇḍala Offering
      parent: Offering
    b01d66983eca41cebf9df2df3e7c0161:
      title: Thirty-Seven Point Maṇḍala Offering
      parent: Offering
    6d0afc3e48b44bff9dd587f3db08a138:
      title: Töpa Gyatsoma Offering Prayer
      parent: Offering
    9610e1e22b9b4de298ed887c977803e3:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Sādhanas
created_at: '2022-02-28T22:43:55.173971'
last_modified_at: '2022-02-28T22:43:55.173974'
